
#ifndef CSGO_CHEAT_SOURCE_SDK_GAME_CLIENT_ICLIENTMODE_HPP_
#define CSGO_CHEAT_SOURCE_SDK_GAME_CLIENT_ICLIENTMODE_HPP_

#include "memory/vtable_util.hpp"

struct IClientMode : mem::VTableUtil
{
};

#endif //CSGO_CHEAT_SOURCE_SDK_GAME_CLIENT_ICLIENTMODE_HPP_
